### ISSUE TITLE
docker_login module tracebacks in ansible 2.9.24 (working in 2.9.23)

### ISSUE THREAD

**Issue by zach-prometheus** [ansible-collections/community.docker#187]
##### SUMMARY

Originally filed under https://github.com/ansible/ansible/issues/75378

After upgrading to ansible 2.9.24 invoking the docker_login module gives the following error:

Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on marcus-dex-00's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name certs

Downgrading to 2.9.23, the module works correctly.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_login
##### ANSIBLE VERSION

```paste below
ansible 2.9.24
  config file = /Users/1234567/local_repo/ansible.cfg
  configured module search path = ['/Users/1234567/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/1234567/ansible/2.9/lib/python3.9/site-packages/ansible
  executable location = /Users/1234567/ansible/2.9/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/Users/1234567/local_repo/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/1234567/local_repo/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=5m -o ForwardAgent=yes
DEFAULT_BECOME(/Users/1234567/local_repo/ansible.cfg) = True
DEFAULT_FORKS(/Users/1234567/local_repo/ansible.cfg) = 5
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/1234567/local_repo/ansible.cfg) = ['/Users/1234567/local_repo/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/1234567/local_repo/ansible.cfg) = This file is managed by Ansible. Do not make changes here - they will be overwritten!
DEFAULT_ROLES_PATH(/Users/1234567/local_repo/ansible.cfg) = ['/Users/1234567/local_repo/roles']
DEFAULT_STDOUT_CALLBACK(/Users/1234567/local_repo/ansible.cfg) = debug
RETRY_FILES_ENABLED(/Users/1234567/local_repo/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target environment: Ubuntu 18.04

Local environment: MacOS Big Sur (11.4)

##### STEPS TO REPRODUCE

Attempt to use the docker_login module using ansible 2.9.24 against an Ubuntu 18.04 target.

```yaml
- hosts: example
  tasks:
  - name: install docker packages
    apt:
      name:
      - docker.io
      - python-docker
  - name: login to the docker registry
    docker_login:
      url: "registry.example.com"
      username: "foobar"
      password: "correcthorsebatterystaple"
```

##### EXPECTED RESULTS

The module logs in to the docker registry.

##### ACTUAL RESULTS

The module tracebacks with the below output

```paste below
Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on marcus-dex-00's Python /usr/bin/python. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name certs
```

**Comment by felixfontein** [comment]
It looks like there is a problem with Docker SDK for Python (/usr/bin/python) as installed on your remote (marcus-dex-00). When trying to import it, apparently a dependency fails (called `certs`).

This is not a bug in the module, but a problem with your environment.

**Comment by zach-prometheus** [comment]
This may very well be - how do you suggest I proceed? Doing "pip install ansible==2.9.23" in the virtualenv where I'm running this fixes the issue, so I assume whatever changed in 2.9.24 was previously masking the issue.

**Comment by felixfontein** [comment]
You can manually run the Python ansible is using on the remote and try what the following results in:
```
from docker.errors import DockerException
from docker import auth
if hasattr(auth, 'decode_auth'):
    from docker.auth import decode_auth
else:
    from docker.auth.auth import decode_auth
```
If you are using the correct Python on the correct machine, you should get an error with `cannot import name certs`.

**Comment by felixfontein** [comment]
In any case, you seem to be using the modules from Ansible 2.9, not from this collection; in Ansible 2.9, the modules did not change between 2.9.23 and 2.9.24.
