### ISSUE TITLE
Bug in sanitize_labels method

### ISSUE THREAD

**Issue by zoligorbe** [ansible-collections/community.docker#1028]
I have encountered the following issue:
```
...ansible_collections/community/docker/plugins/module_utils/util.py\", line 285, in fail\r\nAttributeError: 'AnsibleModule' object has no attribute 'fail'...
```

This was introduced with https://github.com/ansible-collections/community.docker/pull/985, most likely a typo/mistake.

The problem is [here](https://github.com/ansible-collections/community.docker/blob/9e26c4794e867ed7ca077febebfcdddb1d9e0561/plugins/module_utils/util.py#L285)

This:
```python
            client.module.fail(msg)
```
should be changed to:
```python
            client.module.fail_json(msg)
```

Can you please fix it as it breaks the module instead of showing the actual error.

Cheers 🍻

**Comment by felixfontein** [comment]
Thanks for reporting this!
